ubox: ignore Werror=format-truncation build failure
Upstream code quality issues most likely due to updated GCC.
It'd be best to fix the warning upstream or patch it proper
but for now just ignore it.

Error:
| kmodloader.c:93:32: error: '/modules/' directive output may
| be truncated writing 9 bytes into a region of size between
| 1 and 256 [-Werror=format-truncation=]
| snprintf(path, sizeof(path), "%s" DEF_MOD_PATH, s, ver.release);
| kmodloader.c:39:23: note: format string is defined here
|    39 | #define DEF_MOD_PATH "/modules/%s/"
|       |                       ^~~~~~~~~
| kmodloader.c:93:3: note: 'snprintf' output between 11 and 330
| bytes into a destination of size 256
|    93 |   snprintf(path, sizeof(path), "%s" DEF_MOD_PATH, s, ver.release);
|       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| cc1: all warnings being treated as errors

Signed-off-by: Matthew Stanger <stangerm2@gmail.com>