xtables-addons: fix build error with linux kernel v4.15 and later
1. The current xtables-addons v3.0 fetch fails with below error:
-- snip --
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '.../.wget-hsts'. HSTS will be disabled.
--2018-03-04 12:53:23--  http://downloads.sourceforge.net/project/xtables-addons/Xtables-addons/xtables-addons-3.0.tar.xz
-- snip --

Also, we cannot find source tar at
http://downloads.sourceforge.net/project/xtables-addons/Xtables-addons/xtables-addons-3.0.tar.xz,
hence use alternate URL
https://fossies.org/linux/privat/xtables-addons-3.0.tar.xz to fetch the source.

2. Add fix-to-build-linux-v4.15-and-later.patch to solve below build error with
   Linux kernel v4.15 and later:
-- snip --
| .../tmp/work-shared/qemux86/kernel-source/arch/x86/include/asm/uaccess.h: In function 'set_fs':
| .../tmp/work-shared/qemux86/kernel-source/arch/x86/include/asm/uaccess.h:32:9: error: dereferencing pointer to incomplete type 'struct task_struct'
|   current->thread.addr_limit = fs;
|          ^~
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>