netifd: replace hardcoded lib string to a generic value
1. If libdir is other than /usr/lib/ , then netifd recipe fails to
build with below error:

-- snip --
| cp: target ‘.../tmp_new/work/corei7-64-montavista-linux/netifd/git-r0/image/lib64/netifd/’ is not a directory
| WARNING: .../tmp_new/work/corei7-64-montavista-linux/netifd/git-r0/temp/run.do_install.27647:1 exit 1 from 'cp -dR
--preserve=mode,links .../tmp_new/work/corei7-64-montavista-linux/netifd/git-r0/git/scripts/*
.../tmp_new/work/corei7-64-montavista-linux/netifd/git-r0/image/lib64/netifd/'
-- snip --

2. Also replace hardcoded '/lib' string with ${base_libdir} in network scripts, so that
   dependent scripts are called from correct paths.

3. Include default.script in an alternative binary naming scheme, as netifd's default.script
   conflicts with busybox-udhcpc's default.script as below during
   openwrt-image-base:do_rootfs :

-- snip --
Error: Transaction check error:
file /usr/share/udhcpc/default.script conflicts between attempted installs of busybox-udhcpc-1.24.1-r0.2.corei7_64 and netifd-git-r0.corei7_64
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>