uclient: Remove -Werror from CMake
Add patch to remove -Werror from CMake. If Werror is enable build failed
with error:

http.c:829:23: error: assignment discards 'const' qualifier from
pointer target type [-Werror]
 uh->ussl.server_name = uh->uc.url->host;
 cc1: all warnings being treated as errors

Also remove -Wno-error=discarded-qualifiers from OECMAKE_C_FLAGS, this
option doesn't exist.

Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>