make-ext4fs: Add patch for missing headers
This program fails to build as-is, due to a missing sys
header.

Error:
contents.c:268: undefined reference to `minor'

Signed-off-by: Matthew Stanger <stangerm2@gmail.com>