core: xtables-addons: Fix build error through version upgrade
bitbake fails with error regarding xtables-addons (3.13):
 ERROR: Kernel configuration is invalid.
 include/generated/autoconf.h or include/config/auto.conf are missing.
 Run 'make oldconfig && make prepare' on kernel src to fix it.

This fix gets rid of this error by replacing bb-files
of version 2.14 and 3.13 with only one bb-file of version 3.18.

The patches of the previous two versions are getting applied,
but the necessity of those patches haven't been investigated.