README.md: add meta-networking to prevent dnsmasq dangling .bbappend
Prevent errors when using bitbake-layers to add meta-openwrt layer:

  ERROR: No recipes available for:
    /.../openembedded-core/meta-openwrt/recipes-tweaks/dnsmasq/dnsmasq_%.bbappend
  ERROR: Parse failure with the specified layer added

Also add meta-python since meta-networking depends on it:

  ERROR: Layer 'networking-layer' depends on layer 'meta-python', but this layer is not enabled in your configuration
  ERROR: Parse failure with the specified layer added

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>