ustream-ssl: Upgrade to latest revision
This upgrade also fixes the following error:

    tmp/work/armv5e-poky-linux-musleabi/ustream-ssl/git-r0/git/ustream-openssl.c:
    In function __ustream_ssl_context_new:
    |
    /tmp/work/armv5e-poky-linux-musleabi/ustream-ssl/git-r0/git/ustream-openssl.c:42:3:
    error: TLSv1_2_server_method is deprecated [-Werror=deprecated-declarations]
    |    m = TLSv1_2_server_method();

Signed-off-by: Alejandro Hernandez <aehs29@gmail.com>