luci: Add missing build time dependency
libxcrypt is required to build luci. It's likely this was over
looked via host system bleed though and cmake.

Error:
| libs/luci-lib-nixio/src/user.c:34:10: fatal error: crypt.h:
| No such file or directory
| 34 |  #include <crypt.h>

Signed-off-by: Matthew Stanger <stangerm2@gmail.com>